-- ============================================================================
-- Tenant Seed: {{TENANT_NAME}}
-- ============================================================================
-- Generated by: scripts/provision-tenant.ts
-- Generated at: {{GENERATED_AT}}
--
-- Run this SQL in the tenant's Supabase project SQL Editor to create the
-- tenant row. This must be run AFTER all schema migrations have been applied.
--
-- IMPORTANT: This uses the service role (bypasses RLS). Do not run this
-- from a client application.
-- ============================================================================

INSERT INTO public.tenants (
  id,
  name,
  subdomain,
  custom_domain,
  logo_url,
  primary_color,
  secondary_color,
  feature_flags
)
VALUES (
  '{{TENANT_ID}}',
  '{{TENANT_NAME}}',
  '{{TENANT_SUBDOMAIN}}',
  '{{TENANT_DOMAIN}}',
  {{LOGO_URL}},
  '{{PRIMARY_COLOR}}',
  '{{SECONDARY_COLOR}}',
  '{
    "admissions": true,
    "crm": true,
    "messaging": true,
    "classes": true,
    "instructor_marketplace": true,
    "stripe_payments": true,
    "stripe_identity": true,
    "zoom_integration": true,
    "remarketing": true,
    "white_label": false
  }'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  subdomain = EXCLUDED.subdomain,
  custom_domain = EXCLUDED.custom_domain,
  logo_url = EXCLUDED.logo_url,
  primary_color = EXCLUDED.primary_color,
  secondary_color = EXCLUDED.secondary_color,
  updated_at = now();
